### ISSUE TITLE
有没有组织讨论这个

### ISSUE THREAD

**Issue by daowang** [OpeningO/JFinal-ext2#7]
启动不起来，
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

db.ds = mysql
db.mysql.active = true
db.mysql.url = 127.0.0.1/test
db.mysql.user = root
db.mysql.password =111111
db.mysql.initsize = 10
db.mysql.maxactive = 100
db.showsql = true
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Caused by: java.lang.IllegalArgumentException: String length must be a multiple of four.
	at com.alibaba.druid.util.Base64.base64ToByteArray(Base64.java:128)
	at com.alibaba.druid.util.Base64.base64ToByteArray(Base64.java:110)
	at com.alibaba.druid.filter.config.ConfigTools.decrypt(ConfigTools.java:146)
	at com.alibaba.druid.filter.config.ConfigFilter.decrypt(ConfigFilter.java:203)
	... 13 more

**Comment by daowang** [comment]
Exception in thread "main" java.lang.IllegalArgumentException: Failed to decrypt.
	at com.alibaba.druid.filter.config.ConfigFilter.decrypt(ConfigFilter.java:211)
	at com.alibaba.druid.filter.config.ConfigFilter.init(ConfigFilter.java:123)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:511)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:876)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:872)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:97)
	at com.jfinal.plugin.activerecord.generator.MetaBuilder.build(MetaBuilder.java:90)
	at com.jfinal.plugin.activerecord.generator.Generator.generate(Generator.java:210)
	at com.jfinal.ext2.config.JFinalConfigExt.getDruidPlugin(JFinalConfigExt.java:328)
	at com.jfinal.ext2.config.JFinalConfigExt.configPlugin(JFinalConfigExt.java:146)
	at com.jfinal.ext2.config.StandaloneDbConfig$JFinalSubConfig.<init>(StandaloneDbConfig.java:71)
	at com.jfinal.ext2.config.StandaloneDbConfig.<init>(StandaloneDbConfig.java:37)
	at com.jfinal.ext2.config.StandaloneDbConfig.startGe(StandaloneDbConfig.java:55)
	at com.jfinal.ext2.ge.Ge.main(Ge.java:31)
Caused by: java.lang.IllegalArgumentException: String length must be a multiple of four.
	at com.alibaba.druid.util.Base64.base64ToByteArray(Base64.java:128)
	at com.alibaba.druid.util.Base64.base64ToByteArray(Base64.java:110)
	at com.alibaba.druid.filter.config.ConfigTools.decrypt(ConfigTools.java:146)
	at com.alibaba.druid.filter.config.ConfigFilter.decrypt(ConfigFilter.java:203)
	... 13 more
